### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by aamir-067** [bennjii/open-pos#7]
Kindly update and redeploy the demo. this not working. thanks.

![Screenshot 2024-09-25 at 11 33 12 AM](https://github.com/user-attachments/assets/5a442e76-48ec-41ee-88da-98098a22c042)

**Comment by aamir-067** [comment]
the application also require a pin when I try to run it locally. and there is no password given.

**Comment by bennjii** [comment]
Sorry about that, didn’t see the first notification! Apologies, this project is considered archived for the time being, since I haven’t had any time to work on it in a few months, even my knowledge of the codebase is a bit rusty.

However, to run it you’ll need to run a MySQL instance locally, then when you run the open-stock program it will migrate the schema automatically, given it can connect. Then, you can connect to your local DB using your preferred client and add an employee with a desired PIN (“pass” column if I recall). There is an admin portal program, which allows for user creation that is currently private since it contains proprietary information, but if I get some more time to work on it I can clean that up and make it public.

**Comment by aamir-067** [comment]
no worry, I'll try. thanks
